/*
Count(H, N)
activate_and_wait(window_name, wait_seconds, attempts)
activate_and_wait_only(window_name, wait_seconds)
activate_black_box_report()
activate_blotter()
activate_operation_completed()
add_day(d)
append_to_front_of_box_description(append_txt)
backup(file_name, name, i_folder)
backup_compiled_files()
backup_compiled_files_helper(box_name, i_folder)
backup_compiled_files_if_changed(ustate, box_name)
backup_compiled_path(box_name, component)
basket_manager_new_basket()
basket_manager_private_tab_selected()
basket_manager_sub_folder_selected()
basket_vars_changed(i_vars, bu_vars)
break_down_launch_rule_into_cycles(schedule_cycles, start_year, start_month, start_half, end_year, end_month, end_half, cycle_names)
break_down_launch_rule_into_slash_cycles(start_year, start_month, start_half, end_year, end_month, end_half, start_cycles, end_cycles)
btq_action_press_ok()
build_box_description
build_box_name
build_bu_path(code_component, name)
build_c_path(code_component)
build_i_path(code_component)
build_local_box
build_local_box_version
capture_equity_curve()
change_just_the_description(cycle_name)
change_just_the_launch_rule(lr)
check_select_all()
click_activate_and_wait(calling_window, expected_window, click_x, click_y, wait_seconds, attempts)
click_all_records()
click_and_confirm_bbd_tab(x, y, index)
click_backtesting()
click_backtesting_time_interval_tab()
click_basket_manager_filter_text_box()
click_basket_manager_ok_button()
click_basket_manager_private_tab()
click_basket_manager_run_filter()
click_basket_manager_sub_folder()
click_choose_basket()
click_common_order_parameters_tab()
click_configuration_box_save()
click_create_blotter_button()
click_create_custom_blotter_name_box()
click_custom_blotter_name_filter_box()
click_custom_blotter_name_first_row()
click_custom_blotter_tab()
click_design_tab()
click_design_tab_no_confirm()
click_edit_basket_save_button()
click_end_date()
click_launch_rule_tab()
click_launch_rule_tab_no_confirm()
click_live()
click_multi_day_radio_button()
click_name_box()
click_onde_day_date()
click_one_day_radio_button()
click_operation_completed_ok_button()
click_options_tab()
click_order_form_save_button()
click_primus_blotter_tab()
click_primus_stop_order_tab()
click_refresh()
click_risk_management_tab()
click_select_all()
click_start_date()
click_symbols_tab()
click_validate_and_close()
clipboard_paste
clipboard_simple_paste
clipboard_simple_paste_followed_by_enter
compile_code_files()
compile_code_files_if_changed(ustate)
compile_code_folder(code_folder)
configuration_activate()
confirm_basket_manager_is_open()
confirm_code_files_exist()
confirm_compiled_files_exist()
confirm_file_exists(path)
confirm_image_search_files_exist()
confirm_order_type(type)
confirm_requisite_file_for_update(box_name)
confirm_requisite_files()
copy_cutom_functions_from_expression_builder()
create_15_day_launch_rule(year, month, half)
create_15_day_launch_rule_slash_style(year, month, half, byref out_start_date, byref out_end_date)
create_backup_folder()
create_backup_folder_helper(box_name)
create_custom_blotter(box_name)
create_cycle_name(y, m, h)
created_count(str)
current_queue_size(str)
custom_blotter_open()
cyclify_launch_rule(cycle, launch_rule)
date_convert_from_ahk(ahk_date)
date_convert_to_ahk(d)
email_attachment(subj,msg,file)
email_message(subj,msg)
enter_box_name_filter(box_name)
enter_date(month, day, year)
entry_confirm_trigger(rule)
entry_open_existing_order()
entry_open_new_order()
entry_update_trigger(rule)
entry_vars_changed(i_vars, bu_vars)
expression_builder_activate()
expression_click_clear()
expression_click_edit_custom_expression()
expression_click_ok()
expression_set_code(rule)
finalize_build()
find_box
gcc_initial_compile()
generic_code_parser(file_name, array)
get_backup_compiled
get_code_files_update_status(box_name, array)
get_design_tab_checkboxes(checkbox_array)
get_edit_basket_checkboxes(checkboxes)
get_jobs()
get_local_compiled
get_max_runs()
get_options_variables(ops)
get_order_form_check_boxes(checkboxes)
get_previous_trading_date()
get_risk_management_tab_vars(vars)
get_timestamp()
get_top_file(path)
git_clone(box_name, branch_name)
git_commit_bu()
git_push_bu()
hour_glass_sleep(millis)
image_search(window_title, start_x, start_y, end_x, end_y, image_path)
image_search_from_0(window_title, end_x, end_y, image_path)
image_search_simple(x,y,path)
in_progress_count(str)
inform(msg)
inform_activation_error(window_name)
inform_timeout(msg, seconds)
inform_timeout_pause_option(msg, seconds)
information_click_ok()
is_checked
is_off_all_records()
is_off_backtesting()
is_off_live()
launch_rules_changed(i_vars, bu_vars)
launcher_activate()
launcher_click_diagnostics()
launcher_click_edit_box()
launcher_click_gear()
launcher_click_new_box()
launcher_click_open_box()
launcher_click_play()
launcher_click_queue_manager()
launcher_click_save_as()
launcher_click_save_box()
launcher_click_wrench()
list_files(path)
load_csv_dictionary(file_path, output_array)
load_jobs(file_path, output_array)
local_compiled_path(box_name, component)
log(msg)
log_trace(msg, file, function, line)
maintenance_count(str)
move_completed_job_file(file_name)
number_of_active_runs_for_box(box_name)
number_of_free_slots()
number_of_updated_files(array)
online_count(str)
open_ael_how_expression_builder()
open_ael_price_increment_expression_builder()
open_ael_time_increment_expression_builder()
open_ael_trigger_expression_builder()
open_black_box_search_results_empty()
open_blackbox_activate()
open_blackbox_click_close()
open_blackbox_click_first_row()
open_blackbox_click_open()
open_blackbox_folder_search_mode_toggle()
open_blackbox_search_click()
open_blackbox_search_field_focus()
open_create_custom_blotter()
open_existing_basket(name)
open_limit_price_expression_builder()
open_new_bb_design()
open_paint_app()
open_stop_price_expression_builder()
open_trail_how_expression_builder()
open_trail_increment_expression_builder()
options_vars_changed(ti_vars, pi_vars, tbu_vars, pbu_vars)
paint_app_activate()
paint_app_close()
paint_app_paste_clipboard()
paint_app_save_as(path)
pause_mechanism()
process_custom_blotter_form(box_name)
process_test_results(box_name)
quick_inform(msg)
read_csv_file(file_name)
read_lines(file_name)
remove_git_dir(box_name)
risk_management_changed(i_vars, bu_vars)
run_cmd
run_date_cycle(start_year, start_month, start_half, end_year, end_month, end_half)
save_black_box_reports()
save_blackbox_click_save()
select_all_checked()
select_custom_blotter(blotter_name)
selected_bbdesign_tab()
send_mail(emailToAddress,emailPass,emailFromAddress,emailSubject,emailMessage, fileLocation)
send_mail_plain(emailToAddress,emailPass,emailFromAddress,emailSubject,emailMessage)
set_backtesting_date_intervals(start_month, start_day, start_year, end_month, end_day, end_year)
set_basket()
set_basket_always_exclude_symbols(symbols)
set_basket_description(desc)
set_basket_hard_to_borrow_allowed_symbols(symbols)
set_basket_helper(basket, version)
set_basket_name(name)
set_basket_rule(rule)
set_basket_symbols(symbols)
set_black_box_scheme(scheme)
set_black_box_side(side)
set_check_box
set_check_box_confirm
set_entry()
set_entry_helper(entry)
set_general_setting()
set_general_settings_helper(i_vars)
set_general_settings_helper_version(i_vars, version)
set_launch_rule(rule)
set_launch_rules()
set_launch_rules_helper(lr)
set_maximum_order_shares(shares)
set_options()
set_options_helper(timeo, pos)
set_order_form_TIF(tif)
set_order_form_TIF2(tif)
set_order_form_TIF2_seconds(seconds)
set_order_form_TIF_seconds(seconds)
set_order_form_destination(dest)
set_order_form_order_side(side)
set_order_form_order_type(type)
set_position_sizing_scheme(code)
set_risk_management()
set_risk_management_helper(rm)
set_stop()
set_stop_helper(stop)
set_target()
set_target_helper(target)
set_time_option(trigger_point, time)
stop_open_existing_order()
stop_open_new_order()
stop_vars_changed(i_vars, bu_vars)
strip_existing_launch_rule_name_in_description(desc)
subtract_day(d)
target_open_existing_order()
target_open_new_order()
target_vars_changed(i_vars, bu_vars)
task_queue_manager_select_and_copy_all()
trace(msg, file, function, line, wait_time := 0)
trigger_check_box
turn_all_records_on()
turn_backtesting_on()
turn_live_on()
update_basket(name)
update_basket_helper(i_vars, bu_vars, version)
update_box
update_box_description(desc)
update_box_dynamic_version
update_box_name(box_name)
update_entry(name)
update_entry_helper(i_vars, bu_vars)
update_general_setting(name)
update_general_setting_helper(i_vars, bu_vars)
update_general_setting_helper_version(i_vars, bu_vars, version)
update_launch_rules(name)
update_launch_rules_helper(i_vars, bu_vars)
update_options(name)
update_options_helper(ti_vars, pi_vars, tbu_vars, pbu_vars)
update_risk_management(name)
update_risk_management_helper(i_vars, bu_vars)
update_stop(name)
update_stop_helper(i_vars, bu_vars)
update_target(name)
update_target_helper(i_vars, bu_vars)
updated(code_component, name)
wait_activate_if_error(window_name, wait_seconds, attempts)
wait_activate_popup_error(window_name, wait_seconds, attempts)
wait_only(window_name, wait_seconds)
wait_until_idle(seconds)
wait_until_sec_or_enter(seconds)
wait_until_with_message(seconds, msg_txt)
waiting_for_run_count(str)
word_count(str, word)
*/
