; windows
#include header

build_local_box(box_name)
{
  log_trace("entered", A_ScriptName, A_ThisFunc, A_LineNumber)
  quick_inform("build_local_box")
  create_backup_folder_helper(box_name)
  pause_mechanism()
  open_new_bb_design()
  pause_mechanism()
  set_general_settings_helper(get_local_compiled(box_name, "general_settings"))
  pause_mechanism()
  set_entry_helper(get_local_compiled(box_name, "entry"))
  pause_mechanism()
  set_target_helper(get_local_compiled(box_name, "target"))
  pause_mechanism()
  set_stop_helper(get_local_compiled(box_name, "stop"))
  pause_mechanism()
  set_basket_helper(get_local_compiled(box_name, "basket"), "0.0")
  pause_mechanism()
  set_options_helper(get_local_compiled(box_name, "time_options"),get_local_compiled(box_name, "position_sizing"))
  pause_mechanism()
  set_risk_management_helper(get_local_compiled(box_name, "risk_management"))
  pause_mechanism()
  set_launch_rules_helper(get_local_compiled(box_name, "launch_rules"))
  pause_mechanism()
  backup_compiled_files_helper(box_name, "")
  pause_mechanism()
  click_validate_and_close()
  pause_mechanism()
  launcher_click_save_as()
  pause_mechanism()
  save_blackbox_click_save()
  pause_mechanism()
  information_click_ok()
  pause_mechanism()
}

build_local_box_version(box_name, box_version)
{
  log_trace("entered", A_ScriptName, A_ThisFunc, A_LineNumber)
  quick_inform("build_local_box")
  create_backup_folder_helper(box_name)
  open_new_bb_design()
  pause_mechanism()
  set_general_settings_helper_version(get_local_compiled(box_name, "general_settings"), box_version)
  pause_mechanism()
  set_entry_helper(get_local_compiled(box_name, "entry"))
  pause_mechanism()
  set_target_helper(get_local_compiled(box_name, "target"))
  pause_mechanism()
  set_stop_helper(get_local_compiled(box_name, "stop"))
  pause_mechanism()
  set_basket_helper(get_local_compiled(box_name, "basket"), box_version)
  pause_mechanism()
  set_options_helper(get_local_compiled(box_name, "time_options"),get_local_compiled(box_name, "position_sizing"))
  pause_mechanism()
  set_risk_management_helper(get_local_compiled(box_name, "risk_management"))
  pause_mechanism()
  set_launch_rules_helper(get_local_compiled(box_name, "launch_rules"))
  pause_mechanism()
  backup_compiled_files_helper(box_name, "")
  pause_mechanism()
  click_validate_and_close()
  pause_mechanism()
  launcher_click_save_as()
  pause_mechanism()
  save_blackbox_click_save()
  pause_mechanism()
  information_click_ok()
  pause_mechanism()
}
