; windows
#include window_basket_manager.ahk
#include window_black_box_design.ahk
#include window_black_box_report.ahk
#include window_btq_action.ahk
#include window_configuration.ahk
#include window_edit_basket.ahk
#include window_expression_builder.ahk
#include window_information.ahk
#include window_launcher.ahk
#include window_order_form.ahk
#include window_save_blackbox.ahk
#include window_task_queue_manager.ahk
; tabs
#include tab_design.ahk
#include tab_symbols.ahk
#include tab_options.ahk
#include tab_risk_management.ahk
#include tab_launch_rule.ahk
; utilities
#include box_builder.ahk
#include box_finder.ahk
#include box_name_builder.ahk
#include box_updater.ahk
#include check_boxes.ahk
#include code_parser.ahk
#include dates.ahk
#include files.ahk
#include gcc_compile.ahk
#include inform.ahk
#include launch_rule_cycle.ahk
#include logger.ahk
#include wait_policy.ahk
